name: Issue assignment

on:
  issues:
    types: [opened]

jobs:
  assign-issue:
    uses: yeencloud/ci/.github/workflows/issue.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}